spring.application.name=sgl
spring.datasource.url=jdbc:mysql://localhost:3306/wonderland_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true